
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: postgres
  password: root

development:
  <<: *default
  database: UploadXD_development


test:
  <<: *default
  database: UploadXD_test


production:
  <<: *default
  database: UploadXD_production
  username: UploadXD
  password: <%= ENV['UPLOADXD_DATABASE_PASSWORD'] %>
